### ISSUE TITLE
Formatting of `os.environ` wraps on the os.environ

### ISSUE THREAD

**Issue by ChrisCarini** [grantjenks/blue#48]
Something about this just reads/seems strange to me - it's not what I'd expect.
```
-        os.environ['JAVA_HOME'] = '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/'
+        os.environ[
+            'JAVA_HOME'
+        ] = '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/'
```

**Comment by grantjenks** [comment]
I think it would be better if Black had chosen:
```
os.environ['JAVA_HOME'] = (
    '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/'
)
```
But it can't do that because introducing the parens would change the AST (which it strictly forbids as a sanity check so that it doesn't change semantics).

You're options then are to:
1. Disable formatting somehow on this line (e.g. #28)
2. Change the diff yourself to use parens. (Black/Blue won't complain then.)
3. Increase the line length.
4. Introduce a variable like:
```
java_home_path = '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/'
os.environ['JAVA_HOME'] = java_home_path
```
But I don't see anything blue or black could otherwise do here (while still adhering to the line-length rule and no-ast-changes rule).

**Comment by warsaw** [comment]
Bummer, but I agree with your analysis.
